exclude: pelican/plugins/filetime_from_git/

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args:
          - "--from-first"
          - "--multi-line=VERTICAL_HANGING_INDENT"
          - "--trailing-comma"
          - "--thirdparty=pelican"
- repo: https://github.com/PyCQA/docformatter
  rev: v1.5.0
  hooks:
    - id: docformatter
      args:
        - --in-place
        - --pre-summary-newline
        - --make-summary-multi-line
-   repo: https://github.com/rstcheck/rstcheck
    rev: 'v6.1.1'
    hooks:
    -   id: rstcheck
        args: [--report-level=warning]
