exclude: pelican/plugins/filetime_from_git/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - name: black
        id: black
        args: ["--line-length", "79"]
  - repo: https://github.com/rstcheck/rstcheck
    rev: 'v6.2.5'
    hooks:
      - id: rstcheck
        args: [--report-level=warning]
