exclude: pelican/plugins/filetime_from_git/

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args:
          - "--from-first"
          - "--multi-line=VERTICAL_HANGING_INDENT"
          - "--trailing-comma"
          - "--thirdparty=pelican"
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
    - id: docformatter
      args:
        - --in-place
        - --pre-summary-newline
        - --make-summary-multi-line
-   repo: https://github.com/myint/rstcheck
    rev: '3f92957478422df87bd730abde66f089cc1ee19b'
    hooks:
    -   id: rstcheck
        args: [--report=warning]
