exclude: pelican/plugins/filetime_from_git/

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
    -   id: isort
        args:
          - "--from-first=yes"
          - "--multi-line=VERTICAL_HANGING_INDENT"
          - "--trailing-comma"
          - "--thirdparty=pelican"
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args:
        - --in-place
        - --pre-summary-newline
        - --make-summary-multi-line
